# Generated by Django 5.0.14 on 2025-11-29 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.CharField(max_length=50, verbose_name='หมายเลขเครื่อง (PC ID)')),
                ('installed_sw', models.TextField(blank=True, null=True, verbose_name='Software ประจำเครื่อง')),
                ('user_type', models.CharField(choices=[('student', 'นักศึกษา'), ('staff', 'เจ้าหน้าที่/บุคลากร'), ('external', 'บุคคลภายนอก')], max_length=10, verbose_name='ประเภทผู้ใช้')),
                ('user_id', models.CharField(max_length=50, verbose_name='รหัสประจำตัว/เลขบัตร ปชช.')),
                ('user_name', models.CharField(max_length=100, verbose_name='ชื่อ-นามสกุล')),
                ('faculty', models.CharField(blank=True, max_length=100, null=True, verbose_name='คณะ/หน่วยงาน')),
                ('year_level', models.IntegerField(blank=True, null=True, verbose_name='ชั้นปี')),
                ('education_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='ระดับการศึกษา')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='หน่วยงานภายนอก')),
                ('checkin_time', models.DateTimeField(verbose_name='เวลาเข้า')),
                ('checkout_time', models.DateTimeField(blank=True, null=True, verbose_name='เวลาออก')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='ระยะเวลา (นาที)')),
                ('rating', models.IntegerField(default=5, verbose_name='คะแนน')),
                ('comment', models.TextField(blank=True, verbose_name='ข้อเสนอแนะ')),
            ],
            options={
                'verbose_name': 'บันทึกการใช้งาน',
                'verbose_name_plural': 'ประวัติการใช้งาน',
                'ordering': ['-checkin_time'],
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('pc_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='หมายเลขเครื่อง (PC ID)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
            ],
            options={
                'verbose_name': 'เครื่องคอมพิวเตอร์',
                'verbose_name_plural': 'จัดการเครื่องคอมพิวเตอร์',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, verbose_name='รหัสนักศึกษา/ผู้จอง')),
                ('pc', models.CharField(blank=True, max_length=20, null=True, verbose_name='หมายเลขเครื่อง')),
                ('software', models.CharField(blank=True, max_length=100, null=True, verbose_name='ซอฟต์แวร์')),
                ('booking_date', models.DateField(verbose_name='วันที่จอง')),
                ('start_time', models.TimeField(verbose_name='เวลาเริ่ม')),
                ('end_time', models.TimeField(verbose_name='เวลาสิ้นสุด')),
            ],
            options={
                'verbose_name': 'รายการจอง',
                'verbose_name_plural': 'ข้อมูลการจอง',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อโปรแกรม')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='เวอร์ชัน')),
            ],
            options={
                'verbose_name': 'ซอฟต์แวร์',
                'verbose_name_plural': 'ข้อมูลซอฟต์แวร์',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('computer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status_info', serialize=False, to='core.computer', verbose_name='เครื่องคอมพิวเตอร์')),
                ('software', models.CharField(blank=True, max_length=100, null=True, verbose_name='Software ประจำเครื่อง')),
                ('status', models.CharField(choices=[('in_use', 'ใช้อยู่'), ('available', 'ว่าง'), ('disabled', 'ปิดใช้บริการ')], default='available', max_length=20, verbose_name='สถานะ')),
                ('current_user_type', models.CharField(blank=True, choices=[('student', 'นักศึกษา'), ('staff', 'เจ้าหน้าที่/บุคลากร'), ('external', 'บุคคลภายนอก')], max_length=10, null=True, verbose_name='ประเภทผู้ใช้')),
                ('current_user_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสประจำตัว/เลขบัตร ปชช.')),
                ('current_user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อ-นามสกุล')),
                ('faculty', models.CharField(blank=True, max_length=100, null=True, verbose_name='คณะ/หน่วยงาน')),
                ('year_level', models.IntegerField(blank=True, null=True, verbose_name='ชั้นปี')),
                ('education_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='ระดับการศึกษา')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='หน่วยงานภายนอก')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='เวลาเริ่มใช้งาน')),
            ],
            options={
                'verbose_name': 'สถานะเครื่อง',
                'verbose_name_plural': 'สถานะเครื่องคอมพิวเตอร์',
            },
        ),
    ]
